### ISSUE TITLE
Commentaire sur onPlayerConnecting

### ISSUE THREAD

**Issue by Ekinoxx0** [NextCitizens/ncs_core#77]
Hi, it looks like this part of code will never be called.

https://github.com/NextCitizens/ncs_core/blob/a6aa12ca4e4ca4ceb69f7e301f458b9429af6927/src/modules/players/server/events/onPlayerConnecting.lua#L7

Context :
In playerConnecting, we will only get a temporary source ID, it's not the final "source".
Generally, this temporary id is assigned above an int16, so 65536 at least.
It is therefore useless to check if this id is already connected to the server knowing that it will never assign this if already used.

Also note : we will rather use a check by main identifier here to find out if the player is already connected, depending on the future of the framework, either check by discord, steam, license or other id 👍

Good luck with your framework

**Comment by Wz-FiveM** [comment]
Good evening, thank you for the return, but please explain the problems in English.

**Comment by PABLO-1610** [comment]
> Hi, it looks like this part of code will never be called.
> 
> https://github.com/NextCitizens/ncs_core/blob/a6aa12ca4e4ca4ceb69f7e301f458b9429af6927/src/modules/players/server/events/onPlayerConnecting.lua#L7
> 
> Context : In playerConnecting, we will only get a temporary source ID, it's not the final "source". Generally, this temporary id is assigned above an int16, so 65536 at least. It is therefore useless to check if this id is already connected to the server knowing that it will never assign this if already used.
> 
> Also note : we will rather use a check by main identifier here to find out if the player is already connected, depending on the future of the framework, either check by discord, steam, license or other id 👍
> 
> Good luck with your framework

Hi @Ekinoxx0 😁 

Indeed you are totally right, stupid mistake on my part especially since I had already faced this problem (with a script using it). I think it's because I was tired 🤣 

By the way, if you're available, I'd love to talk to you on Discord since I know you're working with ESX and you're pretty good. I'd really like to get some constructive advice from a developer who has a lot to do with FiveM on how to structure the project to make it as accessible and complete as possible.

As the person in charge of the whole NCS project, the most complex thing in my opinion is really to think about the use of the project, not so much to write the code...

If you feel like discussing it, don't hesitate to **DM** me, you can find me on the NCS Discord (https://discord.gg/nextcitizens) or my Discord tag is **Pablo'#9969**.
